
exports.up = function(knex) {
  return knex.schema.createTable("users", t => {
    t.increments('id')
    t.uuid('uuid').unique()
    t.string('email').unique()
    t.string('password').notNullable()
    t.string('access_token')
    t.string('refresh_token')
    t.string('initial_message')
    t.string('repeat_message')
    t.string('youtube_id')
    t.boolean('is_grandfathered')
    t.json('reddit_profile')
  })
  .createTable('contacts', t => {
    t.increments('id')
    t.uuid('uuid')
    t.string('name')
    t.string('notes')
    t.uuid('user_id')
    t.foreign('user_id').references('users.uuid').onDelete("CASCADE")
  })
  .createTable("initial_greeting", t => {
    t.increments('id')
    t.uuid('uuid')
    t.string('text')
    t.uuid('user_id').unique()
    t.foreign('user_id').references('users.uuid').onDelete("CASCADE")
  })
  .createTable("repeat_greeting", t => {
    t.increments('id')
    t.uuid('uuid')
    t.string('text')
    t.uuid('user_id').unique()
    t.foreign('user_id').references('users.uuid').onDelete("CASCADE")
  })
  .createTable('stories', t => {
    t.increments('id')
    t.uuid('uuid')
    t.string('author')
    t.string('flair')
    t.integer('num_comments').unsigned()
    t.string('post_id')
    t.text('self_text', 'longtext')
    t.string('title')
    t.integer('ups').unsigned()
    t.string('url')
    t.string('subreddit')
    t.boolean('permission').defaultTo('false')
    t.boolean('read').defaultTo('false')
    t.uuid('user_id')
    t.foreign('user_id').references('users.uuid').onDelete("CASCADE")
  })
  .createTable('websites', t => {
    t.increments('id')
    t.uuid('uuid')
    t.string('subdomain').unique()
    t.string('title')
    t.string('twitter')
    t.string('facebook')
    t.string('instagram')
    t.string('patreon')
    t.string('youtube')
    t.string('podcast')
    t.string('introduction')
    t.boolean('submission_form').defaultTo('false')
    t.boolean('youtube_timeline').defaultTo('false')
    t.string('youtube_id')
    t.boolean('twitter_timeline').defaultTo('false')
    t.string('twitter_id')
    t.boolean('show_credit_link').defaultTo('true')
    t.string('banner_url').defaultTo('https://images.unsplash.com/photo-1524721696987-b9527df9e512?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2090&q=80')
    t.string('accent').defaultTo('#000000')
    t.string('theme').defaultTo('light')
    t.uuid('user_id').unique()
    t.foreign('user_id').references('users.uuid').onDelete("CASCADE")
  })
  .createTable('stories_used', t => {
    t.increments('id')
    t.string('post_id')
    t.uuid('user_id')
    t.foreign('user_id').references('users.uuid').onDelete("CASCADE")
  })
  .createTable('authors_messaged', t => {
    t.increments('id')
    t.string('name')
    t.uuid('user_id')
    t.foreign('user_id').references('users.uuid').onDelete("CASCADE")
  })

};

exports.down = function(knex) {
  return knex.schema.dropTable('users')
};
