version: "3.3"
services:
  server:
    container_name: reddex_backend
    image: tyrelchambers/reddex
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: "${NODE_ENV}"
    restart: unless-stopped

networks:
  default:
    external:
      name: backend
